# Generated by Django 3.2.12 on 2022-02-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashkey', models.CharField(max_length=100)),
                ('src_app', models.CharField(max_length=20)),
                ('dest_app', models.CharField(max_length=20)),
                ('vpc_id', models.CharField(max_length=20)),
                ('bytes_tx', models.IntegerField()),
                ('bytes_rx', models.IntegerField()),
                ('hour', models.IntegerField()),
            ],
        ),
    ]
