# Generated by Django 3.2.12 on 2022-02-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fas', '0002_flowlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowlog',
            name='id',
        ),
        migrations.AlterField(
            model_name='flowlog',
            name='hashkey',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
